---
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.0.1
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-added-large-files
      - id: check-yaml
      - id: check-ast
      - id: check-merge-conflict
  - repo: https://github.com/adrienverge/yamllint.git
    rev: v1.26.3
    hooks:
      - id: yamllint
        args:
          - .pre-commit-config.yaml
          - .github/workflows/ci.yaml
  - repo: https://github.com/ansible-community/ansible-lint.git
    rev: v6.0.1
    hooks:
      - id: ansible-lint
        always_run: false
        files: ^tasks/.*\.(yaml|yml)
